map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 8000 default_server;
    server_name _; # Wildcard is fine here, we're validating a header token instead
    resolver 8.8.8.8;
    client_header_buffer_size 4k;
    large_client_header_buffers 4 16k;

    # Setup log files
    access_log /var/log/nginx/poker_access.log;
    error_log /var/log/nginx/poker_error.log info;

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 'healthy';
    }

    # Dynamic Location Block for WebSocket Routing
    location ~ ^/game/(?<port_num>\d+)$ {
        # Verify header token so that we only accept requests from cloudfront
        if ($http_x_origin_verify != "TOKEN_PLACEHOLDER") {
            return 403;
        }

        rewrite ^/game/\d+$ / break;

        proxy_pass http://127.0.0.1:$port_num;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade; # References your map block above

        # Standard Network Transparency Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering to guarantee near-zero lag packet delivery
        proxy_buffering off;

        # WebSocket Long-Think Timeouts
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
    
    # Default handler for any requests that don't match the dynamic path
    location / {
        return 404; # Not Found 
    }
}