server {
    listen 80;
    server_name localhost; 

    # Setup log files
    access_log /var/log/nginx/poker_access.log;
    error_log /var/log/nginx/poker_error.log;

    # Dynamic Location Block for WebSocket Routing
    location ~ ^/game/(\d+)$ {
        set $game_port $1; 
        proxy_pass http://localhost:$game_port; 

        # Boilerplate websocket headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
        proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
        proxy_read_timeout 86400s;
    }
    
    # Default handler for any requests that don't match the dynamic path
    location / {
        return 404; # Not Found 
    }
}