syntax = "proto3";

package poker_api;

// Network

// Used for client side deserialization
message HttpResponseWrapper {
    int32 result = 1;
    int32 response_code = 2;
    repeated string response_headers = 3;
    bytes response_body = 4;
}

message ErrorResponse {
    string message = 1;
    string error = 2;
}

// Account

message AccountRecord {
    string accountId = 1;
    string playerName = 2;
    int64 createTimeEpochMilliseconds = 3;
    string profilePictureUrl = 4;
    int32 handsWon = 5;
    int32 handsPlayed = 6;
    string playerColor = 7;
    string friendCode = 8;
}

message AccountRecordList {
  repeated AccountRecord records = 1;
}

// Game

message GameRecord {
    string gameId = 1;
    string hostAccountId = 2;
    GameStatus gameStatus = 3;
    int64 createTimeEpochMilliseconds = 4;
    int64 endTimeEpochMilliseconds = 5;
    int32 port = 6;
    int32 blindChips = 7;
    int32 buyInChips = 8;
    int32 chipRatio = 9;
    int32 handsPlayed = 10; 
    repeated string connectedPlayers = 11;
    GamePrivacy gamePrivacy = 12;
}

message GameRecordList {
  repeated GameRecord records = 1;
}

enum GameStatus {
    STARTING = 0;
    ACTIVE = 1;
    ENDED = 2;
}

enum GamePrivacy {
    PUBLIC = 0; // Anyone can join as long as they know the game id
    FRIENDS = 1; // Only friends of the host can join
    INVITE = 2; // Only players with an invite code can join (TBD)
    PRIVATE = 3; // Only host can join, play against bots
}

// JoinToken

message JoinTokenRecord {
    string accountId = 1;
    string gameId = 2;
    string joinToken = 3;
    int64 expirationTimeEpochMilliseconds = 4;
}

// Relationships

message RelationshipRecord {
    string accountId = 1;
    string peerAccountId = 2;
    RelationshipStatus relationshipStatus = 3;
    string nickname = 4;
    int64 createTimeEpochMilliseconds = 5;
}

message RelationshipRecordList {
    repeated RelationshipRecord relationships = 1;
}

enum RelationshipStatus {
    FRIEND = 0;
    OUTGOING_PENDING = 1;
    INCOMING_PENDING = 2;
    BLOCKED = 3;
    FAVORITE = 4;
}